import{S as d}from"./assets/vendor-CgTBfC_f.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const m=[{preview:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820__480.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820_1280.jpg",description:"Hokkaido Flower"},{preview:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677_1280.jpg",description:"Container Haulage Freight"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785_1280.jpg",description:"Aerial Beach View"},{preview:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619__340.jpg",original:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619_1280.jpg",description:"Flower Blooms"},{preview:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334__340.jpg",original:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334_1280.jpg",description:"Alpine Mountains"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571_1280.jpg",description:"Mountain Lake Sailing"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272_1280.jpg",description:"Alpine Spring Meadows"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255_1280.jpg",description:"Nature Landscape"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843_1280.jpg",description:"Lighthouse Coast Sea"}];let g=new d(".gallery a",{captionsData:"alt",captionDelay:250});function l(){const t=document.querySelector(".gallery");if(!t)return;const a=m.map(i=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${i.original}">
            <img
                class="gallery-image"
                src="${i.preview}"
                alt="${i.description}"
            />
        </a>
    </li>
  `).join("");t.innerHTML=a,g.refresh()}let s={email:"",message:""};const c="gfeedback-form-state";function p(){const t=document.querySelector(".feedback-form");if(!t)return;const a=JSON.parse(localStorage.getItem(c));a&&(s=a,t.elements.email.value=a.email||"",t.elements.message.value=a.message||""),t.addEventListener("input",i=>{s[i.target.name]=i.target.value.trim(),localStorage.setItem(c,JSON.stringify(s))}),t.addEventListener("submit",i=>{i.preventDefault();const n=t.elements.email.value.trim(),e=t.elements.message.value.trim();if(!n||!e){alert("Fill please all fields");return}console.log({email:n,message:e}),localStorage.removeItem(c),s={email:"",message:""},t.reset()}),setTimeout(()=>t.elements.email.focus(),100)}document.addEventListener("DOMContentLoaded",()=>{window.location.pathname.includes("1-gallery.html")?l():window.location.pathname.includes("2-form.html")&&p();const t=document.querySelectorAll("nav a"),a=document.getElementById("dynamic-content");t.forEach(i=>{i.addEventListener("click",async n=>{n.preventDefault();const e=i.getAttribute("href");try{const r=await(await fetch(e)).text();a.innerHTML=r,e.includes("1-gallery.html")?l():e.includes("2-form.html")&&p()}catch(o){console.error("Error loading content:",o),a.innerHTML="<p>Failed to load content.</p>"}})})});
//# sourceMappingURL=index.js.map
